# Dataset and Model Configuration
dataset: cinic10
model: resnet18_YWX
input_channels: 3
output_channels: 62

# Neural Network Training Hyperparameters
train_batch_size: 8
test_batch_size: 16
num_workers: 4
test_ratio: 0.1
lr: 0.01
lr_decay: 0
lr_decay_epoch: 1
momentum: 0.9
weight_decay: 5e-3
verbose: 0

# Federated Learning Settings
num_communication: 100
num_edge_aggregation: 2
num_local_update: 1
iid: -3
niid_share: 0
edgeiid: -1
frac: 1
num_clients: 30
num_edges: 3
self_sample: -1
sample_mapping: '{"0": 3000, "1": 2000, "2": 5000, "3": 10000, "4": -1}'
seed: 1
dataset_root: '~/train_data'
show_dis: 1
classes_per_client: 1
gpu: 0
mtl_model: 0
global_model: 1
local_model: 0
test_on_all_samples: 1
active_mapping: 1
mapping: '{"0": [0, 1, 2, 13, 14, 15, 18], "1": [3, 4, 5, 10, 11, 16], "2": [6, 7, 8, 9, 12, 17, 19]}'

# Synthetic Dataset Parameters
alpha: 1
beta: 1
dimension: 60
num_class: 10

# Model Attack Parameters
attack_flag: 1
attack_mapping: '{"0": [0, 2], "1": [3], "2": [8]}'
attack_mode: "flip"

# Data Partition Method
partition: 'noniid-labeldir'
beta_new: 10
